### ISSUE TITLE
Numerous "smart match is experimental" warnings under perl 5.18

### ISSUE THREAD

**Issue by chuckadams** [evalEmpire/perl5i#259]
I'm not going to post the entire test suite, since this goes on and on, but it's more than simply cosmetic: some tests actually fail because of these warnings.

    t/datetime.t ................. Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/ARRAY.pm line 35.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/ARRAY.pm line 96.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/Meta/Instance.pm line 106.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/Meta/Instance.pm line 113.
    t/datetime.t ................. ok    
    t/die.t ...................... Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/ARRAY.pm line 35.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/ARRAY.pm line 96.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/Meta/Instance.pm line 106.
    Smartmatch is experimental at /home/chuck/proj/myperl/customperl/modules/tmp/perl5i-v2.11.2/blib/lib/perl5i/2/Meta/Instance.pm line 113.
    t/die.t ...................... 1/? 
    #   Failed test 'normal die stderr'
    #   at t/die.t line 49.
    #          got: 'Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 35.
    # Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 96.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 106.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 113.
    # a noble death at test.plx line 1.
    # '
    #     expected: 'a noble death at test.plx line 1.
    # '
    
    #   Failed test 'die without line stderr'
    #   at t/die.t line 49.
    #          got: 'Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 35.
    # Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 96.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 106.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 113.
    # a noble death
    # '
    #     expected: 'a noble death
    # '
    
    #   Failed test 'die with $! = 5 stderr'
    #   at t/die.t line 49.
    #          got: 'Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 35.
    # Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 96.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 106.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 113.
    # a noble death
    # '
    #     expected: 'a noble death
    # '
    t/die.t ...................... 10/? 
    #   Failed test 'die with $! = 0 and $? = 5 stderr'
    #   at t/die.t line 49.
    #          got: 'Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 35.
    # Smartmatch is experimental at lib/perl5i/2/ARRAY.pm line 96.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 106.
    # Smartmatch is experimental at lib/perl5i/2/Meta/Instance.pm line 113.
    # a noble death
    # '
    #     expected: 'a noble death
    # '

**Comment by schwern** [comment]
Fixed by #261
