### ISSUE TITLE
t/flip.t fails under perl 5.18 due to hash ordering assumptions

### ISSUE THREAD

**Issue by chuckadams** [evalEmpire/perl5i#260]
Test output below.  I'd make a pull request, but I'm a bit pressed for time and the fix is pretty obvious: simply remove the duplicate values from the test hash, since there's no deterministic result you'll get from flipping such hashes as long as key order is randomized.

    t/flip.t ..................... 1/? 
    #   Failed test at t/flip.t line 12.
    #     Structures begin differing at:
    #          $got->{bar} = '2'
    #     $expected->{bar} = '3'
    
    #   Failed test 'Returns hash in list context'
    #   at t/flip.t line 16.
    #     Structures begin differing at:
    #          $got->{bar} = '2'
    #     $expected->{bar} = '3'
    # Looks like you failed 2 tests of 3.
    t/flip.t ..................... Dubious, test returned 2 (wstat 512, 0x200)

**Comment by schwern** [comment]
Fixed by #262
