### ISSUE TITLE
t/require.t fails in 5.18 due to expanded error message

### ISSUE THREAD

**Issue by chuckadams** [evalEmpire/perl5i#263]
5.18 added a "helpful" parenthetical to the error given for a failed require.  This is a pretty simple matter of having the test use a regex match that handles both formats.  Pull request will be incoming shortly.

    #   Failed test at t/require.t line 26.
    #          got: 'Can't locate I/Sure/Dont/Exist.pm in @INC (you may need to install the I::Sure::Dont::Exist module) (@INC contains: no thing) at t/require.t line 25.
    # '
    #     expected: 'Can't locate I/Sure/Dont/Exist.pm in @INC (@INC contains: no thing) at t/require.t line 25.
    # '
    # Looks like you failed 1 test of 11.
    t/require.t .................. 
    Dubious, test returned 1 (wstat 256, 0x100)
    Failed 1/11 subtests

**Comment by schwern** [comment]
Fixed by #264
