### ISSUE TITLE
Null byte on command line on Debian

### ISSUE THREAD

**Issue by daxim** [evalEmpire/perl5i#269]
Security researchers have found crash bugs in perl5i as shipped in Debian Wheezy using Mayhem, an automated bug finding tool. <http://lists.debian.org/debian-devel/2013/06/msg00720.html> I have started communication with the Mayhem team in order to "short-circuit" the middle-men maintainers and get the details (the buggy command-line input, backtrace after crash, etc.) ASAP.

Is there any need to keep the details confidential until the underlying bugs are fixed? If not, I'll publish them just here.

**Comment by xtaran** [comment]
`perl -e 'system "perl5i \x{00} -e"'` seems not the correct way to reproduce it. I cannot reproduce it in Debian Testing (currently having 2.13.0) with that commandline, but I can reproduce it with `perl5i \000 -e` and inside Perl's `system()` with `perl -e 'system("perl5i \\000 -e");'`

**Comment by schwern** [comment]
I can reproduce it on Wheezy/Sid with Perl 5.20.1.

**Comment by schwern** [comment]
I have it.  It was just `perl5i -e`.  It wouldn't check there was an argument after the -e, would read one too far on argv, and then try to printf that.
