### ISSUE TITLE
[PATCH] fix some spelling mistakes on the POD

### ISSUE THREAD

**Issue by gregoa** [evalEmpire/perl5i#294]
In Debian we are currently applying the following patch to perl5i.
We thought you might be interested in it too.

    Description: fix some spelling mistakes on the POD
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-05-29
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libperl5i-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by schwern** [comment]
Thanks! Please send along any other fixes Debian makes.
